#!/bin/bash

# Citation: https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script
while getopts p:o:n:u:i: args
do
	case $args in
		p) port=$OPTARG;;
		o) origin=$OPTARG;;
		n) name=$OPTARG;;
		u) username=$OPTARG;;
		i) keyfile=$OPTARG;;
		?) exit 1;;
	esac
done

dns_server=proj4-dns.5700.network
REPLICAS=(proj4-repl1.5700.network proj4-repl2.5700.network proj4-repl3.5700.network proj4-repl4.5700.network proj4-repl5.5700.network proj4-repl6.5700.network proj4-repl7.5700.network)

# Deploy DNS server
echo "Starting deployment of DNS Server..."

# Managing dns directory
ssh -i $keyfile $username@$dns_server "rm -rf ~/dns; mkdir ~/dns/"

# Secure copying over the needed files 
scp -i $keyfile dnsserver constants.py replicaselector.py geoipdata.mmdb $username@$dns_server:~/dns/
scp -i $keyfile -r geoip2lib $username@$dns_server:~/dns/
scp -i $keyfile -r maxminddblib $username@$dns_server:~/dns/

echo "Successfully deployed DNS Server!!"

echo "--------------------------------------------------------"

# Deploy Replica server
echo "Starting deployment of Replica Servers..."

for replica_server in "${REPLICAS[@]}"
do
	#  Managing http directory
	ssh -i $keyfile $username@$replica_server "rm -rf ~/http; mkdir ~/http/"

	# Secure copying over the needed files 
	scp -i $keyfile httpserver cacher constants.py utils.py pageviews.csv $username@$replica_server:~/http/

	echo "Caching ... "
	# Do the caching 
	ssh -i $keyfile $username@$replica_server "cd http; ./cacher -p $port -o $origin"
done 

echo "Successfully deployed Replica Servers!!"