#!/bin/bash

# Citation: https://www.baeldung.com/linux/use-command-line-arguments-in-bash-script
while getopts p:o:n:u:i: args
do
	case $args in
		p) port=$OPTARG;;
		o) origin=$OPTARG;;
		n) name=$OPTARG;;
		u) username=$OPTARG;;
		i) keyfile=$OPTARG;;
		?) exit 1;;
	esac
done

dns_server=proj4-dns.5700.network
REPLICAS=(proj4-repl1.5700.network proj4-repl2.5700.network proj4-repl3.5700.network proj4-repl4.5700.network proj4-repl5.5700.network proj4-repl6.5700.network proj4-repl7.5700.network)

# Stop DNS server
echo "Stopping DNS Server..."

# Kill all 
ssh -i $keyfile $username@$dns_server "killall -u $username dnsserver"
ssh -i $keyfile $username@$dns_server "killall -u $username python3"

# Remove files
ssh -i $keyfile $username@$dns_server "rm -rf ~/dns"

echo "Successfully stopped DNS Server!!"

echo "--------------------------------------------------------"

# Stop Replica server
echo "Stopping Replica Servers..."

# Kill all 
ssh -i $keyfile $username@$replica_server "killall -u $username httpserver"
ssh -i $keyfile $username@$replica_server "killall -u $username python3"

for replica_server in "${REPLICAS[@]}"
do
	# Remove files
	ssh -i $keyfile $username@$replica_server "rm -rf ~/http"
done
echo "Successfully stopped Replica Servers!!"