name: Run Address Sanitizer
on:
  push:
  pull_request:
  schedule:
    - cron: '13 15 * * SUN'
jobs:
  build:
    name: Address Sanitizer
    runs-on: ubuntu-latest
    env:
      ASAN_OPTIONS: strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:detect_invalid_pointer_pairs=2
      CC: clang
      CFLAGS: -fsanitize=address -Wall -Wextra -Wpedantic -Wformat=2 -Walloca -Wvla -Wimplicit-fallthrough -Wcast-qual -Wconversion -Wshadow -Wundef -Wstrict-prototypes -Wswitch-enum -fstack-protector -D_FORTIFY_SOURCE=2 -Werror
      LDFLAGS: -fsanitize=address
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install libmaxminddb
        run: sudo apt install libmaxminddb-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install tox tox-gh-actions

      - name: Build
        run: python setup.py build

      - name: Test with tox
        run: MM_FORCE_EXT_TESTS=1 tox
