name: Python tests

on:
  push:
  pull_request:
  schedule:
    - cron: '3 15 * * SUN'

jobs:
  build:

    strategy:
      matrix:
        # We don't test on Windows and macOS currently due to issues
        # build libmaxminddb there.
        platform: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]

    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install libmaxminddb
        run: sudo apt install libmaxminddb-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
              python -m pip install --upgrade pip
              pip install tox tox-gh-actions

      - name: Build with Werror and Wall
        run: CFLAGS="-Werror -Wall -Wextra" python setup.py build

      - name: Test with tox
        run: MM_FORCE_EXT_TESTS=1 tox
